name: Build, Test, Release and Deploy

# Konfiguracja uprawnień - niezbędna do aktualizacji repozytorium i publikowania pakietów
permissions:
  contents: write  # Uprawnienia do pushowania zmian i tworzenia release'ów
  packages: write  # Uprawnienia do publikowania obrazów Docker

# Wyzwalacze workflow
on:
  # Uruchamianie przy push do głównej gałęzi - używamy dynamicznego wykrywania nazwy
  push:
    branches:
      - 'master'  # Główna gałąź, zmień jeśli używasz innej nazwy
      - 'main'    # Alternatywna popularna nazwa

  # Uruchamianie ręczne z wyborem typu wersji
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Typ wydania'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch   # Drobne poprawki (zwiększa 0.0.X)
          - minor   # Nowe funkcje (zwiększa 0.X.0)
          - major   # Zmiany łamiące kompatybilność (zwiększa X.0.0)

# Definicja zadań
jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      # Krok 1: Pobierz kod
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Pobierz pełną historię (potrzebne dla tagów i historii commitów)

      # Krok 2: Wykryj nazwę bieżącej gałęzi i zapisz ją jako zmienną
      - name: Get current branch
        id: branch
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Current branch name: $BRANCH_NAME"
          echo "name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      # Krok 3: Konfiguracja Pythona
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Krok 4: Instalacja zależności
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest semver
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Krok 5: Lintowanie kodu (sprawdzanie błędów składniowych)
      - name: Lint with flake8
        id: lint
        continue-on-error: true  # Nie zatrzymuj workflow w przypadku błędów lintowania
        run: |
          # Sprawdzenie tylko krytycznych błędów
          LINT_OUTPUT=$(flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics)
          echo "::warning::$LINT_OUTPUT"
          
          # Zapisz czy wystąpiły błędy
          if [ -n "$LINT_OUTPUT" ]; then
            echo "Znaleziono problemy w kodzie, sprawdź szczegóły w logach"
            echo "has_errors=true" >> $GITHUB_OUTPUT
          else
            echo "Analiza kodu przebiegła pomyślnie"
            echo "has_errors=false" >> $GITHUB_OUTPUT
          fi

      # Krok 6: Generowanie i walidacja wersji
      - name: Generate and Validate Version
        id: version
        run: |
          # Funkcja do inkrementacji wersji w zależności od podanego typu wydania
          increment_version() {
            local version=$1
            local type=$2
      
            # Sprawdź, czy wersja jest w poprawnym formacie SemVer (np. 1.0.0)
            if [[ ! $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Niepoprawny format wersji w pliku version.txt lub brak poprawnej wersji. Ustawiam domyślną wersję 1.0.0."
              version="1.0.0"
            fi
      
            # Rozdziel wersję na części: major, minor, patch
            IFS='.' read -r major minor patch <<< "$version"
      
            # Inkrementuj odpowiednią część wersji w zależności od typu wydania
            case $type in
              major)
                major=$((major + 1))
                minor=0
                patch=0
                ;;
              minor)
                minor=$((minor + 1))
                patch=0
                ;;
              patch|*)  # Domyślnie inkrementuj patch (np. 0.0.X)
                patch=$((patch + 1))
                ;;
            esac
      
            # Zwróć nową wersję
            echo "$major.$minor.$patch"
          }
      
          # Pobierz typ wydania (major, minor, patch) z wejścia workflow
          RELEASE_TYPE="${{ github.event.inputs.release_type }}"
          RELEASE_TYPE=${RELEASE_TYPE:-patch}  # Domyślnie ustaw patch, jeśli brak wartości
      
          # Odczytaj wersję z pliku version.txt, jeśli istnieje
          if [ -f "version.txt" ]; then
            VERSION=$(cat version.txt | tr -d '[:space:]')  # Usuń białe znaki
          else
            VERSION="1.0.0"  # Ustaw domyślną wersję, jeśli plik nie istnieje
          fi
      
          # Wygeneruj nową wersję z inkrementacją
          NEW_VERSION=$(increment_version "$VERSION" "$RELEASE_TYPE")
      
          # Walidacja wygenerowanej wersji
          if [[ ! "$NEW_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Błąd: Wygenerowana wersja '$NEW_VERSION' jest nieprawidłowa."
            exit 1
          fi
      
          # Wyprowadź poprawną wersję do pliku version.txt i outputs
          echo "clean_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "$NEW_VERSION" > version.txt
          echo "Wygenerowana wersja: $NEW_VERSION"

      # Krok 7: Commitowanie zmian w pliku version.txt
      - name: Commit version file
        id: commit
        run: |
          # Pobierz nazwę bieżącej gałęzi z poprzedniego kroku
          BRANCH_NAME="${{ steps.branch.outputs.name }}"
          echo "Bieżąca gałąź: $BRANCH_NAME"
          
          # Konfiguracja Git
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          
          # Sprawdź, czy plik version.txt został zmieniony
          if [[ -n "$(git status --porcelain version.txt)" ]]; then
            echo "Plik version.txt został zmieniony, tworzę commit..."
            
            # Dodaj plik version.txt do stage
            git add version.txt
            
            # Utwórz commit
            git commit -m "Aktualizacja version.txt do wersji ${{ steps.version.outputs.VERSION }}"
            
            # Wypchnij zmiany do repozytorium
            echo "Wypychanie zmian do gałęzi $BRANCH_NAME..."
            git push origin HEAD:${BRANCH_NAME}
            
            echo "Zaktualizowano plik version.txt w repozytorium"
            echo "committed=true" >> $GITHUB_OUTPUT
          else
            echo "Plik version.txt nie uległ zmianie, pomijam commit"
            echo "committed=false" >> $GITHUB_OUTPUT
          fi

      # Krok 8: Generowanie changelog
      - name: Generate changelog
        id: changelog
        run: |
          # Użyj odpowiedniego punktu odniesienia do wyszukiwania commitów
          if [[ "${{ steps.commit.outputs.committed }}" == "true" ]]; then
            echo "Poprzedni commit zawierał aktualizację version.txt, uwzględniam w changelog"
            # Użyj HEAD~1 jako bazy, aby uwzględnić ostatni commit aktualizujący wersję
            GIT_REF_BASE="HEAD~1"
          else
            echo "Poprzedni commit nie zawierał aktualizacji version.txt"
            GIT_REF_BASE="HEAD"
          fi
          
          # Pobierz commity od ostatniego taga lub początku historii
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          
          if [ -z "$LAST_TAG" ]; then
            echo "Nie znaleziono tagów, pobieram wszystkie commity (maksymalnie 20)"
            # Jeśli nie ma tagów, weź wszystkie commity (ale ogranicz do 20)
            COMMIT_LIST=$(git log --pretty=format:"%h||%an||%s" --reverse | tail -n 20)
          else
            echo "Znaleziono tag $LAST_TAG, pobieram commity od tego tagu"
            # Jeśli są tagi, weź commity od ostatniego taga
            COMMIT_LIST=$(git log ${LAST_TAG}..${GIT_REF_BASE} --pretty=format:"%h||%an||%s" --reverse)
          fi
          
          # Przygotuj mapę kategorii zmian - używamy zwykłych identyfikatorów jako kluczy
          declare -A CATEGORIES
          CATEGORIES=(
            ["fix"]="Poprawki błędów"
            ["feat"]="Nowe funkcje"
            ["docs"]="Dokumentacja"
            ["style"]="Formatowanie kodu"
            ["refactor"]="Refaktoryzacja"
            ["perf"]="Optymalizacja"
            ["test"]="Testy"
            ["build"]="Build"
            ["ci"]="CI/CD"
            ["chore"]="Porządki"
          )
          
          # Mapa emoji dla każdej kategorii - używana tylko do wyświetlania
          declare -A CATEGORY_EMOJIS
          CATEGORY_EMOJIS=(
            ["fix"]="🐛"
            ["feat"]="✨"
            ["docs"]="📚"
            ["style"]="💎"
            ["refactor"]="♻️"
            ["perf"]="🚀"
            ["test"]="🧪"
            ["build"]="🔧"
            ["ci"]="🤖"
            ["chore"]="🧹"
            ["other"]="🔄"
          )
          
          # Funkcja sprawdzająca typ commita
          get_commit_type() {
            local commit_msg="$1"
            
            for type in "${!CATEGORIES[@]}"; do
              if [[ "$commit_msg" == "$type"* || "$commit_msg" == *"[$type]"* || "$commit_msg" == *"($type)"* ]]; then
                echo "$type"
                return
              fi
            done
            
            # Domyślnie, jeśli nie rozpoznano typu
            echo "other"
          }
          
          # Inicjalizacja zmiennych dla każdej kategorii - używamy bezpiecznych identyfikatorów
          for type in "${!CATEGORIES[@]}"; do
            eval "${type}_commits=''"
          done
          other_commits=""
          
          # Sprawdź, czy lista commitów jest pusta
          if [ -z "$COMMIT_LIST" ]; then
            echo "Nie znaleziono żadnych commitów od ostatniego tagu"
          else 
            echo "Znaleziono commity, przetwarzam..."
            
            # Przetwarzanie commitów i grupowanie ich
            while IFS= read -r line; do
              if [ -z "$line" ]; then
                continue
              fi
              
              # Parsuj linię na hash, autora i wiadomość, zabezpieczając przed specjalnymi znakami
              IFS='||' read -r hash author message <<< "$line"
              
              if [ -z "$hash" ] || [ -z "$message" ]; then
                echo "Pominięto niewłaściwy format commita: $line"
                continue
              fi
              
              # Określ typ commita
              commit_type=$(get_commit_type "$message")
              
              # Usuń prefix typu z treści commita, z dodatkowym zabezpieczeniem przed błędami
              clean_message=$(echo "$message" | sed -E 's/^(feat|fix|docs|style|refactor|perf|test|build|ci|chore)(\([^)]+\))?:\s*//g' | sed -E 's/\[(feat|fix|docs|style|refactor|perf|test|build|ci|chore)\]\s*//g' | sed -E 's/\((feat|fix|docs|style|refactor|perf|test|build|ci|chore)\)\s*//g')
              
              # Zabezpiecz tekst przed specjalnymi znakami w bash
              clean_message=$(echo "$clean_message" | sed 's/"/\\"/g')
              
              # Ładne formatowanie wpisu changelog z linkiem do commita
              formatted_entry="* ${clean_message} [${hash}](https://github.com/${{ github.repository }}/commit/${hash})"
              
              # Dodaj do odpowiedniej kategorii
              if [ "$commit_type" != "other" ]; then
                # Używamy zmiennej z bezpieczną nazwą
                eval "${commit_type}_commits=\"\${${commit_type}_commits}\n${formatted_entry}\""
              else
                other_commits="${other_commits}\n${formatted_entry}"
              fi
            done <<< "$COMMIT_LIST"
          fi
          
          # Przygotowanie każdej sekcji
          FINAL_CHANGELOG=""
          
          # Dodaj sekcje tylko jeśli mają zawartość
          for type in "${!CATEGORIES[@]}"; do
            # Pobierz zawartość z bezpiecznej zmiennej
            eval "commits=\${${type}_commits}"
            
            if [ -n "$commits" ]; then
              emoji="${CATEGORY_EMOJIS[$type]}"
              category_name="${CATEGORIES[$type]}"
              FINAL_CHANGELOG="${FINAL_CHANGELOG}### ${emoji} ${category_name}\n${commits}\n\n"
            fi
          done
          
          # Dodaj inne zmiany (jeśli są)
          if [ -n "$other_commits" ]; then
            emoji="${CATEGORY_EMOJIS[other]}"
            FINAL_CHANGELOG="${FINAL_CHANGELOG}### ${emoji} Inne zmiany${other_commits}\n\n"
          fi
          
          # Jeśli nie ma zmian, dodaj informację
          if [ -z "$FINAL_CHANGELOG" ]; then
            FINAL_CHANGELOG="Brak zmian od ostatniego wydania."
          fi
          
          # Zapisz changelog do pliku
          echo "# 📦 MCServerWatchdog v${{ steps.version.outputs.VERSION }}" > changelog.md
          echo "" >> changelog.md
          echo "Data wydania: $(date +'%d.%m.%Y')" >> changelog.md
          echo "" >> changelog.md
          echo -e "## 📋 Lista zmian\n" >> changelog.md
          echo -e "$FINAL_CHANGELOG" >> changelog.md
          echo "## 📊 Statystyki" >> changelog.md
          echo "- Wersja: ${{ steps.version.outputs.VERSION }}" >> changelog.md
          
          # Liczba commitów
          if [ -n "$COMMIT_LIST" ]; then
            COMMIT_COUNT=$(echo "$COMMIT_LIST" | wc -l)
            echo "- Liczba commitów: $COMMIT_COUNT" >> changelog.md
            
            # Lista autorów
            AUTHORS=$(echo "$COMMIT_LIST" | cut -d'||' -f2 | sort | uniq | tr '\n' ', ' | sed 's/,\s*$//')
            if [ -n "$AUTHORS" ]; then
              echo "- Autorzy: $AUTHORS" >> changelog.md
            else
              echo "- Autorzy: Nieznani" >> changelog.md
            fi
          else
            echo "- Liczba commitów: 0" >> changelog.md
            echo "- Autorzy: Brak nowych commitów" >> changelog.md
          fi
          
          # Zapisz changelog jako output
          # Użyj heredoc formatu dla zachowania znaków nowej linii
          echo 'CHANGELOG<<EOF' >> $GITHUB_OUTPUT
          cat changelog.md >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      # Krok 9: Przygotowanie tagów Docker (zastąpienie + na -)
      - name: Prepare Docker tags
        id: docker_tags
        run: |
          # Pobierz wersję
          VERSION="${{ steps.version.outputs.VERSION }}"
          
          # Zastąp znak + na - w wersji dla tagu Dockera
          DOCKER_VERSION="${VERSION//+/-}"
          echo "Docker tag version: $DOCKER_VERSION"
          
          # Zapisz zmienną do outputs
          echo "version=$DOCKER_VERSION" >> $GITHUB_OUTPUT

      # Krok 10: Konfiguracja Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Krok 11: Logowanie do GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Krok 12: Budowanie i publikowanie obrazu Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mcserverwatchdog:latest
            ghcr.io/${{ github.repository_owner }}/mcserverwatchdog:${{ steps.docker_tags.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Krok 13: Tworzenie tagu Git dla wersji
      - name: Create Git Tag
        run: |
          # Konfiguracja Git
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          
          # Pobierz wersję
          VERSION="${{ steps.version.outputs.VERSION }}"
          echo "Tworzenie tagu Git dla wersji: v$VERSION"
          
          # Utwórz tag lokalnie
          git tag -a "v$VERSION" -m "Version $VERSION"
          
          # Wypchnij tag do repozytorium
          git push origin "v$VERSION"
          echo "Tag v$VERSION został utworzony i wysłany do repozytorium"

      # Krok 14: Tworzenie wydania na GitHubie
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: Release v${{ steps.version.outputs.VERSION }}
          body: "${{ steps.changelog.outputs.CHANGELOG }}"
          draft: false
          prerelease: false
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Krok 15: Podsumowanie wykonania workflow
      - name: Summary
        run: |
          echo "### 📦 MCServerWatchdog Deployment" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Wersja**: v${{ steps.version.outputs.VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "🏷️ **Docker tag**: ghcr.io/${{ github.repository_owner }}/mcserverwatchdog:${{ steps.docker_tags.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "📅 **Data wydania**: $(date +'%d.%m.%Y %H:%M:%S')" >> $GITHUB_STEP_SUMMARY
          
          # Dodaj informację o lintowaniu
          if [[ "${{ steps.lint.outputs.has_errors }}" == "true" ]]; then
            echo "⚠️ **Ostrzeżenie**: Wykryto problemy w kodzie podczas lintowania" >> $GITHUB_STEP_SUMMARY
          else
            echo "✅ **Linting**: Kod przeszedł wszystkie testy" >> $GITHUB_STEP_SUMMARY
          fi
          
          # Dodaj link do wydania
          echo "🔗 **Link do wydania**: [v${{ steps.version.outputs.VERSION }}](https://github.com/${{ github.repository }}/releases/tag/v${{ steps.version.outputs.VERSION }})" >> $GITHUB_STEP_SUMMARY