name: Create Installation Package Only

# Ten workflow tylko tworzy paczkę instalacyjną, nie zmienia wersji i nie tworzy release'u

permissions:
  contents: read  # Tylko odczyt repo

on:
  workflow_dispatch:
    inputs:
      version_override:
        description: 'Opcjonalne nadpisanie wersji (jeśli puste, użyje version.txt)'
        required: false
        type: string

jobs:
  create-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version from file or input
        id: version
        run: |
          # Sprawdź czy podano nadpisanie wersji
          OVERRIDE="${{ github.event.inputs.version_override }}"
          
          if [ -n "$OVERRIDE" ]; then
            # Użyj podanej wersji
            echo "Używam podanej wersji: $OVERRIDE"
            echo "version=$OVERRIDE" >> $GITHUB_OUTPUT
          elif [ -f "version.txt" ]; then
            # Użyj wersji z pliku
            VERSION=$(cat version.txt | tr -d '[:space:]')
            echo "Odczytana wersja z pliku: $VERSION"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            # Domyślna wersja
            echo "Nie znaleziono pliku version.txt, używam wersji testowej"
            echo "version=test-build" >> $GITHUB_OUTPUT
          fi

      - name: Create installation package
        id: create_package
        run: |
          set -ex  # Zatrzymaj przy błędzie i wyświetlaj komendy
          
          # Zainstaluj zip
          sudo apt-get update && sudo apt-get install -y zip
          
          # Sprawdź czy zip działa
          zip --version
          
          # Utwórz nazwę pliku ZIP
          VERSION="${{ steps.version.outputs.version }}"
          ZIP_FILENAME="mcserverwatchdog-v${VERSION}.zip"
          echo "Tworzenie paczki: ${ZIP_FILENAME}"
          
          # Przygotuj katalog tymczasowy
          rm -rf temp_package || true
          mkdir -p temp_package
          
          # Skopiuj pliki
          for file in main.py pretty_logger.py version.txt requirements.txt; do
            if [ -f "$file" ]; then
              echo "Kopiowanie $file"
              cp "$file" temp_package/
            else
              echo "UWAGA: Brak pliku $file"
            fi
          done
          
          # Skopiuj .env.example jeśli istnieje
          if [ -f ".env.example" ]; then
            cp ".env.example" temp_package/.env.example
          fi
          
          # Utwórz plik README
          cat > temp_package/README.txt << EOF
          MCServerWatchdog v${VERSION}
          ===========================
          
          Aby uruchomić bota:
          1. Upewnij się, że masz Pythona 3.10+
          2. Zainstaluj zależności: pip install -r requirements.txt
          3. Skopiuj .env.example do .env i uzupełnij
          4. Uruchom: python main.py
          
          Więcej na: https://github.com/${{ github.repository }}
          EOF
          
          # Listuj zawartość katalogu
          echo "Zawartość katalogu temp_package:"
          ls -la temp_package/
          
          # Utwórz archiwum ZIP
          cd temp_package
          zip -r "../${ZIP_FILENAME}" ./*
          cd ..
          
          # Sprawdź czy plik ZIP istnieje
          if [ -f "${ZIP_FILENAME}" ]; then
            echo "Paczka utworzona pomyślnie"
            ls -lh "${ZIP_FILENAME}"
            echo "filename=${ZIP_FILENAME}" >> $GITHUB_OUTPUT
          else
            echo "ERROR: Nie udało się utworzyć paczki"
            exit 1
          fi

      - name: Upload package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: installation-package
          path: ${{ steps.create_package.outputs.filename }}
          retention-days: 7

      - name: Summary
        run: |
          echo "### 📦 Paczka instalacyjna" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Wersja**: v${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "📥 **Plik**: ${{ steps.create_package.outputs.filename }}" >> $GITHUB_STEP_SUMMARY
          echo "Możesz pobrać paczkę z sekcji Artifacts powyżej" >> $GITHUB_STEP_SUMMARY